# This is a basic workflow to help you get started with Actions

name: Build APK

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: 'v*'
    branches: [ master ]
  pull_request:
    tags: 'v*'
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Build Android App
  # You may pin to the exact commit or the version.
  # uses: sparkfabrik/android-build-action@02e36921259edb617c8395c1432b3164b3257e8e
        uses: sparkfabrik/android-build-action@v1.0.0
        with:
          # Project path
          project-path: GRAPHER
          # Output path of apk
          output-path: GRAPHER.apk # optional, default is output.apk
          # Name of the gradle task to exec
          ## gradle-task: # optional, default is assembleDebug
          # Boolean to tell the Action to upload the .ipa to Browserstack App Live after the build.
          ## browserstack-upload: # optional
          ## Browserstack username (required if browserstack-upload == true)
          #browserstack-username: # optional, default is 
          # Browserstack access key (required if browserstack-upload == true)
          ##browserstack-access-key: # optional, default is 
